---
- name: Create docker-compose file for new stagging environment
  template:
    src: docker-compose.yml.j2
    dest: "{{ working_dir }}/docker-compose.yml"

- name: Pull stagging image
  shell: "docker pull {{DOKER_REPO_URL}}/{{REPO_NAME}}/{{APP_NAME}}:{{APP_VERSION}}"

- name: Start database container
  shell: "docker-compose up -d mariadb"
  args:
    chdir: "{{working_dir}}"

- name: Wait for database up
  wait_for:
    host: 127.0.0.1
    port: "{{ DB_PORT }}"
    delay: 10
    timeout: 300

- name: Start app container
  shell: "docker-compose up -d opencpsv2-portal"
  args:
    chdir: "{{working_dir}}"

- name: Wait for app container up
  wait_for:
    host: 127.0.0.1
    port: "{{ OPENCPSV2_PORT }}"
    delay: 10
    timeout: 300