---
- name: Create docker-compose file for new stagging environment
  template:
    src: docker-compose.yml.j2
    dest: "{{ working_dir }}/docker-compose.yml"

- name: Pull stagging image
  shell: "docker pull {{docker_repo_uri}}/{{stagging_repo}}/{{app_name}}.{{app_version}}"

- name: Start app container
  shell: "docker-compose up -d"
  args:
    chdir: "{{working_dir}}"