---
- name: Ensure working dir exists
  file:
    state: directory
    path: "{{working_dir}}"

- name: Check if docker-compose exists
  stat:
    path: "{{working_dir}}/docker-compose.yml"
  register: docker_compose_details

- debug:
    msg: "Docker compose exists"
  when: docker_compose_details.stat.exists

- name: Ensure  application stop and remove old data
  shell: "docker-compose down -v --rmi all"
  args:
    chdir: "{{working_dir}}"
  when: docker_compose_details.stat.exists
  ignore_errors: yes

- name: Clean environment
  file:
    state: "{{item}}"
    path: "{{working_dir}}"
  with_items:
  - absent
  - directory

- name: Install pip
  easy_install:
    name: pip
  become: True

- name: Install docker SDK for python
  pip:
    name: docker
    state: latest
  become: True