
version: '3.3'
services:
  jenkins:
    # image: jenkinsci/blueocean:1.8.2
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50001:50000
    container_name: jenkins
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock